/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docsSidebar: [
    {
      type: 'doc',
      id: 'Overview',
    },
    {
      type: 'category',
      label: 'Whitepaper',
      // link: {
      //   type: 'doc',
      //   id: 'whitepaper/Entry/Introduction',
      // },
      items: [
            {
              type: 'category',
              label: 'Entry',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Entry/Introduction',
              // },
              items: [
                'whitepaper/Entry/Introduction',
                'whitepaper/Entry/WhatWeNeed',
              ],
            },
            {
              type: 'category',
              label: 'Features',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Features/BiometricSmartContract',
              // },
              items: [
                'whitepaper/Features/BiometricSmartContract',
                'whitepaper/Features/KadeshWill',
                'whitepaper/Features/KadeshBox',
                'whitepaper/Features/KadeshChain',
                'whitepaper/Features/KadeshWallet',
              ],
            },
            {
              type: 'category',
              label: 'Token',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Token/KDSToken',
              // },
              items: [
                'whitepaper/Token/KDSToken',
                'whitepaper/Token/TokenUtility',
                'whitepaper/Token/TokenFlow',
                'whitepaper/Token/TokenAllocation',
                'whitepaper/Token/TokenEmission',
              ],
            },
            {
              type: 'category',
              label: 'Revenue Model',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Revenue Model/Monetization',
              // },
              items: [
                'whitepaper/Revenue Model/Monetization',
              ],
            },
            {
              type: 'category',
              label: 'Market Info',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Market Info/TargetMarkets',
              // },
              items: [
                'whitepaper/Market Info/TargetMarkets',
                'whitepaper/Market Info/Competitors',
              ],
            },
            {
              type: 'doc',
              id: 'whitepaper/Roadmap/Roadmap',
            },
            {
              type: 'category',
              label: 'Team',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Team/CoreTeam',
              // },
              items: [
                'whitepaper/Team/CoreTeam',
                'whitepaper/Team/Resumes',
              ],
            },
            {
              type: 'category',
              label: 'References',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/References/WebApp',
              // },
              items: [
                'whitepaper/References/WebApp',
                'whitepaper/References/MobileApp',
              ],
            },
            {
              type: 'category',
              label: 'Legal',
              // link: {
              //   type: 'doc',
              //   id: 'whitepaper/Legal/Disclaimer',
              // },
              items: [
                'whitepaper/Legal/Disclaimer',
              ],
            },
      ],
    },
    {
      type: 'link',
      label: 'Chain',
      href: '/docs/Chain',
    }
  ],
};

export default sidebars;
