/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Kadesh Docs",
  "favicon": "img/favicon.ico",
  "url": "https://docs.kadeshchain.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ],
    [
      "redocusaurus",
      {
        "specs": [
          {
            "route": "/docs/Chain",
            "spec": "https://raw.githubusercontent.com/KadirBerat/KadeshYml/main/openapi3.yml"
          }
        ]
      }
    ]
  ],
  "scripts": [
    {
      "src": "https://docs.kadeshchain.com/js/custom.js",
      "async": false
    }
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "alt": "Kadesh",
        "src": "img/kadesh/logo.svg",
        "href": "/docs/Overview"
      },
      "items": [
        {
          "to": "https://kadeshchain.com",
          "position": "left",
          "label": "Home"
        },
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "https://www.kadeshchain.com/Explorer",
          "label": "Explorer",
          "position": "left"
        },
        {
          "to": "https://www.kadeshchain.com/Wallet",
          "label": "Wallet",
          "position": "left"
        },
        {
          "to": "https://www.kadeshchain.com/Faucet",
          "label": "Faucet",
          "position": "left"
        },
        {
          "to": "https://dual0.kadesh-testnet.hub5.net:3001/",
          "label": "API",
          "position": "left"
        },
        {
          "to": "https://facebook.com/kadeshchain",
          "className": "facebook-link social-link",
          "position": "left"
        },
        {
          "to": "https://twitter.com/kadeshchain",
          "className": "twitter-link social-link",
          "position": "left"
        },
        {
          "to": "https://linkedin.com/company/kadeshchain",
          "className": "linkedin-link social-link",
          "position": "left"
        },
        {
          "to": "https://instagram.com/kadeshchain",
          "className": "instagram-link social-link",
          "position": "left"
        },
        {
          "to": "https://t.me/kadeshchain",
          "className": "telegram-link social-link",
          "position": "left"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div id=\"docsearch\"></div>"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "© Kadeshchain All Rights Reserved.",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "P8L48VCRQH",
      "apiKey": "a8a771e2ad19b583d319b66ef3c0485c",
      "indexName": "kadeshchain",
      "contextualSearch": false,
      "searchPagePath": false,
      "container": "#docsearch",
      "searchParameters": {}
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "tagline": "",
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
